### PR TITLE
overlay: dual band wifi is not supported on l70p

### PR DESCRIPTION
**Pull request by g-pl**
Change-Id: I0d1be0ce4fd3f75ccede375730f71c663cb56d8b

### CODE REVIEW

**Comment by geekydoc** [comment]
Hey, thanks for contributing to this project! Are you interested in becomimg a collaborator? What device are you on?

**Comment by g-pl** [comment]
Hi, sure I'd like, it would simplify the workflow. I'm on D290N.
Thanks for all your work on this project!

**Comment by geekydoc** [comment]
Ok, i think i added you on all repos. Do you have a xda account I can contact you on?

**Comment by g-pl** [comment]
Thanks, g-pl on xda

**Pull request merged**
